CREATE DATABASE PA302
USE PA302
CREATE TABLE Students(
Id INT  PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR (50)DEFAULT 'XXX',
FinCode CHAR(7) NOT NULL UNIQUE,
Age INT CHECK(Age>=10),
AvgPoint DECIMAL(5,2) CHECK(AvgPoint>=0 AND AvgPoint<=100)

DELETE FROM Students WHERE AvgPoint=0
UPDATE Students SET AvgPoint=100 WHERE AvgPoint=99
SELECT*FROM Students WHERE Avgpoint>51 AND AvgPoint<90
SELECT*FROM Students WHERE [Name] LIKE 'a%f'